
 CREATE OR REPLACE PACKAGE PACKAGE_REGLA_NEGOCIO
 
 
 AS 
 
 PROCEDURE SP_INSERCION;
 
 
 
 
 
 END; 

CREATE OR REPLACE PACKAGE BODY PACKAGE_REGLA_NEGOCIO


IS




PROCEDURE SP_INSERCION 


IS

V_PROPIEDAD_A_INGRESAR PROPIEDAD%ROWTYPE;
V_MAYOR_ID NUMBER(4);


BEGIN
SELECT NVL(MAX(NRO_PROPIEDAD), 0)
INTO V_MAYOR_ID
FROM PROPIEDAD;
EXECUTE IMMEDIATE 'CREATE SEQUENCE SEQ_ID_PROPIEDAD START WITH ' || (V_MAYOR_ID + 1);
SELECT SEQ_ID_PROPIEDAD.NEXTVAL INTO V_PROPIEDAD_A_INGRESAR.NRO_PROPIEDAD FROM dual;
V_PROPIEDAD_A_INGRESAR.FECHA_ENTREGA_PROPIEDAD := TO_DATE('&FECHA_ENTREGA_PROPIEDAD', 'DD/MM/YYYY');
V_PROPIEDAD_A_INGRESAR.DIRECCION_PROPIEDAD := '&DIRECCION_PROPIEDAD';
V_PROPIEDAD_A_INGRESAR.SUPERFICIE := TO_NUMBER(&SUPERFICIE);
V_PROPIEDAD_A_INGRESAR.NRO_DORMITORIOS := TO_NUMBER(&DORMITORIOS);
V_PROPIEDAD_A_INGRESAR.NRO_BANOS := TO_NUMBER(&NRO_BANOS);
V_PROPIEDAD_A_INGRESAR.VALOR_ARRIENDO := TO_NUMBER(&VALOR_ARRIENDO);
V_PROPIEDAD_A_INGRESAR.VALOR_GASTO_COMUN := TO_NUMBER(&VALOR_GASTO_COMUN);
V_PROPIEDAD_A_INGRESAR.NUMRUT_PROP := TO_NUMBER(&NUMRUT_PROP);
V_PROPIEDAD_A_INGRESAR.ID_COMUNA :=TO_NUMBER(&ID_COMUNA);
V_PROPIEDAD_A_INGRESAR.ID_TIPO_PROPIEDAD :='&ID_TIPO_PROPIEDAD';
DBMS_OUTPUT.PUT_LINE('ID Propiedad: ' || V_PROPIEDAD_A_INGRESAR.NRO_PROPIEDAD);
DBMS_OUTPUT.PUT_LINE('Fecha Entrega: ' || TO_CHAR(V_PROPIEDAD_A_INGRESAR.FECHA_ENTREGA_PROPIEDAD, 'DD/MM/YYYY'));
DBMS_OUTPUT.PUT_LINE('Direccion: ' || V_PROPIEDAD_A_INGRESAR.DIRECCION_PROPIEDAD);
DBMS_OUTPUT.PUT_LINE('Superficie: ' || V_PROPIEDAD_A_INGRESAR.SUPERFICIE);
DBMS_OUTPUT.PUT_LINE('Dormitorios: ' || V_PROPIEDAD_A_INGRESAR.NRO_DORMITORIOS);
DBMS_OUTPUT.PUT_LINE('Baños: ' || V_PROPIEDAD_A_INGRESAR.NRO_BANOS);
DBMS_OUTPUT.PUT_LINE('Valor Arriendo: ' || V_PROPIEDAD_A_INGRESAR.VALOR_ARRIENDO);
DBMS_OUTPUT.PUT_LINE('Gasto Común: ' || V_PROPIEDAD_A_INGRESAR.VALOR_GASTO_COMUN);
DBMS_OUTPUT.PUT_LINE('ID Comuna: ' || V_PROPIEDAD_A_INGRESAR.ID_COMUNA);
DBMS_OUTPUT.PUT_LINE('ID Tipo Propiedad: ' || V_PROPIEDAD_A_INGRESAR.ID_TIPO_PROPIEDAD);
DBMS_OUTPUT.PUT_LINE('RUT Propietario: ' || V_PROPIEDAD_A_INGRESAR.NUMRUT_PROP);
INSERT INTO PROPIEDAD (NRO_PROPIEDAD,
FECHA_ENTREGA_PROPIEDAD,
DIRECCION_PROPIEDAD,
SUPERFICIE,
NRO_DORMITORIOS,
NRO_BANOS, VALOR_ARRIENDO,
VALOR_GASTO_COMUN,
NUMRUT_PROP, ID_COMUNA,
ID_TIPO_PROPIEDAD)VALUES (V_PROPIEDAD_A_INGRESAR.NRO_PROPIEDAD,
V_PROPIEDAD_A_INGRESAR.FECHA_ENTREGA_PROPIEDAD,
V_PROPIEDAD_A_INGRESAR.DIRECCION_PROPIEDAD,
V_PROPIEDAD_A_INGRESAR.SUPERFICIE,
V_PROPIEDAD_A_INGRESAR.NRO_DORMITORIOS,
V_PROPIEDAD_A_INGRESAR.NRO_BANOS,
V_PROPIEDAD_A_INGRESAR.VALOR_ARRIENDO,
V_PROPIEDAD_A_INGRESAR.VALOR_GASTO_COMUN,
V_PROPIEDAD_A_INGRESAR.NUMRUT_PROP,
V_PROPIEDAD_A_INGRESAR.ID_COMUNA,
V_PROPIEDAD_A_INGRESAR.ID_TIPO_PROPIEDAD);
DBMS_OUTPUT.PUT_LINE('Propiedad insertada correctamente.');
END SP_INSERCION ;

end PACKAGE_REGLA_NEGOCIO;